### ISSUE TITLE
Basic auth setup has no effect

### ISSUE THREAD

**Issue by clement-igonet** [wearefrank/charts#23]
Is this the way to set up basic auth in helm chart ?
```yaml
drill:
  overrideConfiguration:
    drillOnYarn: >-
      drill.yarn.http: {
        auth-type: "simple"
        user-name: "bob"
        password: "secret"
      }
```

When checking `/opt/drill/conf/drill-on-yarn.conf` inside de container, as explained in https://drill.apache.org/docs/enabling-web-ui-security/ :
```
drill.yarn.http: {
  auth-type: "simple"
  user-name: "bob"
  password: "secret"
}
```
But no credentials are required when reaching the web UI.
